"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const user_1 = require("../controllers/user");
const session_1 = require("../middlewares/session");
const router = (0, express_1.Router)();
exports.router = router;
router.get("/", session_1.checkJwt, user_1.list);
router.get("/:id", session_1.checkJwt, user_1.single);
router.post("/", session_1.checkJwt, user_1.add);
router.put("/:id", session_1.checkJwt, user_1.update);
router.delete("/:id", session_1.checkJwt, user_1.remove);
router.post("/resetpassword/:id", session_1.checkJwt, user_1.resetpassword);
